---
- import_tasks: setup.yml
  tags: rails_setup

- block:
    - import_tasks: nginx.yml
      tags: rails_nginx

    - import_tasks: puma.yml
      tags: rails_puma

    - import_tasks: monit.yml
      tags: rails_monit
  when: rails_include_web

- import_tasks: sidekiq.yml
  tags: rails_sidekiq
