---
- import_tasks: setup.yml
  tags: rails_setup

- import_tasks: nginx.yml
  tags: rails_nginx
  when: rails_include_web

- import_tasks: puma.yml
  tags: rails_puma
  when: rails_include_web

- import_tasks: sidekiq.yml
  tags: rails_sidekiq
