---
- name: install extra packages for rails
  apt:
    pkg: "{{ rails_extra_packages }}"
    cache_valid_time: 86400 # 1 day

- name: setup logrotation for rails
  template:
    src: rails-logrotate.j2
    dest: /etc/logrotate.d/rails
    mode: 0644
