---
- name: "install nginx server block for {{ rails_codename }}"
  template:
    src: nginx_server_block.conf.j2
    dest: "/etc/nginx/sites-available/{{ rails_codename }}.conf"
  notify: restart nginx

- name: "create symlink to activate {{ rails_codename }}"
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ rails_codename }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ rails_codename }}.conf"
  notify: restart nginx

- name: set up HTTP basic auth
  template:
    src: rails-htpasswd.j2
    dest: "{{ rails_http_auth_htpasswd_file }}"
    mode: 0600
    owner: www-data
  when: rails_http_auth_enabled
  notify: restart nginx
