---
- name: update sidekiq systemd service config
  template:
    src: sidekiq.service.j2
    dest: /lib/systemd/system/sidekiq.service
  notify: restart sidekiq

- name: ensure config directory exists
  file:
    path: "{{ rails_sidekiq_config_dest | dirname }}"
    state: directory

- name: update sidekiq config
  template:
    src: "{{ rails_sidekiq_config }}"
    dest: "{{ rails_sidekiq_config_dest }}"
  notify: restart sidekiq

- name: watch sidekiq with monit
  template:
    src: rails-sidekiq-monit.j2
    dest: /etc/monit/conf.d/sidekiq
    mode: 0600
  notify: reload monit
